#!/bin/bash

# Place in /usr/lib/systemd/system-sleep/xkeyboard
# Note: This only covers unhibernate/waking up, not system startups (use Startup Applications for this)


case $1 in
    pre)
        exit 0
    ;;
    post)
        export DISPLAY=:1
        sleep 5
        /bin/su max -c "sleep 5 && xmodmap /home/max/.Xmodmap"
    ;;
esac
